---
jobs:
  include:
    - stage: test
      cache: ccache
      addons:
        apt:
          packages:
            - cmake
      services:
        - docker
      install:
        - cp taskserver/taskserver.env.example taskserver/taskserver.env
        - cp certbot/certbot.env.example certbot/certbot.env
        - echo 'LE_DISABLE=true' >> taskserver/taskserver.env
        - echo 'LE_DISABLE=true' >> certbot/certbot.env
        - mkdir taskserver/server_certs
        - cp taskserver/client_certs/client.cert.pem.example taskserver/client_certs/client.cert.pem
        - cp taskserver/client_certs/client.key.pem.example taskserver/client_certs/client.key.pem
        - docker-compose up -d
        - curl -L https://taskwarrior.org/download/task-2.5.1.tar.gz -o /tmp/task.tar.gz
        - mkdir /tmp/task
        - tar xzf /tmp/task.tar.gz -C /tmp/task --strip 1
        - cd /tmp/task
        - cmake -DCMAKE_BUILD_TYPE=release .
        - make
        - sudo make install
        - cd -
      script:
        - docker-compose exec taskserver sh -c 'echo $TASKDDATA'
        - export USER_UUID=$(docker-compose exec taskserver sh -c 'ls -1 "$TASKDDATA/orgs/$TASKD_ORGNAME/users"')
        - printf "new user UUID is $USER_UUID"
        - yes | task version
        - ls -clash ~/.task
        - cp taskserver/client_certs/client.cert.pem.example ~/.task/client.cert.pem
        - cp taskserver/client_certs/client.key.pem.example ~/.task/client.key.pem
        - ls -clash taskserver/server_certs/
        - cp taskserver/server_certs/ca.cert.pem ~/.task/ca.cert.pem
        - ls -clash ~/.task
        - yes | task config taskd.certificate -- ~/.task/client.cert.pem
        - yes | task config taskd.key -- ~/.task/client.key.pem
        - yes | task config taskd.ca -- ~/.task/ca.cert.pem
        - yes | task config taskd.server -- localhost:53589
        - yes | task config taskd.credentials -- My Org/user/$USER_UUID
        - yes | task config taskd.trust -- ignore hostname
        - cat ~/.task/config
        - task diagnostics
        - sleep 30
        - yes | task sync init
      after_script:
        - docker-compose logs
