---
jobs:
  include:
    - stage: test
      services:
        - docker
      install:
        - curl -LO https://taskwarrior.org/download/task-2.5.1.tar.gz && tar xzf task-2.5.1.tar.gz
        - cp taskserver/taskserver.env.example taskserver/taskserver.env
        - echo 'LE_DISABLE=true' >> taskserver/taskserver.env
        - cp taskserver/client.cert.pem.example taskserver/client.cert.pem
        - cp taskserver/client.key.pem.example taskserver/client.key.pem
        - cp certbot/certbot.env.example certbot/certbot.env
        - docker up -d
        - export USER_UUID=$(docker-compose exec taskserver ["ls", "-1", "$TASKDDATA/orgs/$TASKD_ORGNAME/users"])
      script: 
        - yes 'yes' | task-2.5.1/task version
        - cp taskserver/client.cert.pem.example ~/.task
        - cp taskserver/client.key.pem.example ~/.task
        - task-2.5.1/task config taskd.certificate -- ~/.task/client.cert.prm
        - task-2.5.1/task config taskd.key -- ~/.task/client.key.prm
        - task-2.5.1/task config taskd.server -- localhost:53589
        - task-2.5.1/task config taskd.credentials -- My Org/user/$USER_UUID
      script: yes 'yes' | task-2.5.1/task sync init
