---
jobs:
  include:
    - stage: test
      services:
        - docker
      install:
        # setup service
        - cp taskserver/taskserver.env.example taskserver/taskserver.env
        - docker-compose up -d
        # wait for taskd to come up
        - sleep 20
        # extract user uuid, needed to configure client
        - docker-compose exec taskserver sh -c 'echo ${TASKDDATA}'
        - export USER_UUID=$(docker-compose exec taskserver sh -c 'ls --color=never -1 "${TASKDDATA}/orgs/${TASKD_ORGNAME}/users"' | sed 's/\r//')
        - printf "new user UUID is ${USER_UUID}"
        # configure client
        - docker create
          --name tw
          --volume `pwd`/taskserver/client_certs:/client_certs:ro
          --network dockertaskdservice_default
          alpine
          yes
        - docker start tw
        - docker exec -it tw sh -c "apk --no-cache add task"
        - docker exec -it tw sh -c "yes | task version"
        - docker exec -it tw sh -c "yes | task config taskd.certificate -- /client_certs/user.cert.pem"
        - docker exec -it tw sh -c "yes | task config taskd.key -- /client_certs/user.key.pem"
        - docker exec -it tw sh -c "yes | task config taskd.ca -- /client_certs/ca.cert.pem"
        - docker exec -it tw sh -c "yes | task config taskd.server -- taskserver:53589"
        - docker exec -it tw sh -c "yes | task config taskd.credentials -- My Org/user/${USER_UUID}"
        - docker exec -it tw sh -c "yes | task diagnostics"
        - docker exec -it tw sh -c "cat ~/.taskrc"
      script:
        - docker exec -it tw sh -c "yes | task sync init"
      after_script:
        - docker-compose logs
