---
jobs:
  include:
    - stage: test
      services:
        - docker
      addons:
        apt:
          packages:
            - task
      install:
        - cp taskserver/taskserver.env.example taskserver/taskserver.env
        - echo 'LE_DISABLE=true' >> taskserver/taskserver.env
        - cp taskserver/client.cert.pem.example taskserver/client.cert.pem
        - cp taskserver/client.key.pem.example taskserver/client.key.pem
        - cp certbot/certbot.env.example certbot/certbot.env
        - docker-compose up -d
      script:
        - export USER_UUID=$(docker-compose exec taskserver ["ls", "-1", "$TASKDDATA/orgs/$TASKD_ORGNAME/users"])
        - "yes | task version"
        - cp taskserver/client.cert.pem.example ~/.task
        - cp taskserver/client.key.pem.example ~/.task
        - yes | task config taskd.certificate -- ~/.task/client.cert.prm
        - yes | task config taskd.key -- ~/.task/client.key.prm
        - yes | task config taskd.server -- localhost:53589
        - yes | task config taskd.credentials -- My Org/user/$USER_UUID
        - "yes | task sync init"
