#!/usr/bin/with-contenv sh
#shellcheck shell=sh

if [ "$LE_DISABLE" = "true" ]; do
  until [ -s /ssl_certs/privkey.pem ]; do
    printf "Waiting for SSL certificates from Lets Encrypt"
    sleep 15
  done
else
  printf "Lets Encrypt disabled, not waiting for certs"
done
