#!/usr/bin/with-contenv sh
#shellcheck shell=sh

printf "Generating certificates\n"
cd /opt/src/taskd/pki || exit 1
# generate self-signed certs
./generate
# move generated certs in place
cp ./client.*.pem /ssl_certs/
cp ./server.*.pem /ssl_certs/
cp ./ca.*.pem /ssl_certs/
cp ./ca.cert.pem /client_certs/
