#!/usr/bin/with-contenv sh
#shellcheck shell=sh

if [ "$LE_DISABLE" = "true" ] && [ ! -s /ssl_certs/domain.key ]; then
  printf "Generating self-signed server certs\n"
  apk --no-cache add curl gnutls-utils
  # get certificate generation scripts from repo
  cd /tmp || exit 1
  curl -sSL https://api.github.com/repos/gothenburgbitfactory/taskserver/tarball/master -o /tmp/taskd.tar.gz
  mkdir /tmp/taskd
  tar xzf taskd.tar.gz -C /tmp/taskd --strip 1
  cd taskd/pki || exit 1
  # generate self-signed certs
  ./generate
  # move generated certs in place
  mv ./*.pem /ssl_certs/
  mv /ssl_certs/server.key.pem /ssl_certs/domain.key
  mv /ssl_certs/server.cert.pem /ssl_certs/domain.crt
  cp /ssl_certs/client.cert.pem /client_certs/client.cert.pem
  cp /ssl_certs/client.key.pem /client_certs/client.key.pem
  cp /ssl_certs/ca.cert.pem /client_certs/ca.cert.pem
  cd /tmp || exit 1
  # cleanup
  rm -rf /tmp/taskd /tmp/taskd.tar.gz
  apk --no-cache del curl gnutls-utils
fi
