#!/usr/bin/with-contenv sh
#shellcheck shell=sh

cp /ssl_certs/domain.crt "$TASKDDATA"
cp /ssl_certs/domain.key "$TASKDDATA"
ls -clash /
ls -clash /client_certs
cp /client_certs/*.pem "$TASKDDATA"
mv "$TASKDDATA/domain.key" "$TASKDDATA/server.key.pem"
mv "$TASKDDATA/domain.crt" "$TASKDDATA/server.cert.pem"
chown -R taskd:taskd "$TASKDDATA"
