#!/usr/bin/with-contenv sh
#shellcheck shell=sh
# with help from https://blog.polettix.it/setup-a-taskwarrior-server/

if [ -s "$TASKDDATA/config" ]; then
  printf "$TASKDDATA/config file found, skipping bootstrap\n"
else
  printf "$TASKDDATA/config file not found, bootstrapping taskd\n"
  taskd add org "$TASKD_ORGNAME"
  taskd add user "$TASKD_ORGNAME" "$TASKD_USERNAME" | grep -oE '[a-f0-9\-]{36}'
  taskd config --force -- server      "$TASKD_DOMAIN:53589"
  taskd config --force -- log         "$TASKDDATA"/taskd.log
  taskd config --force -- pid.file    "$TASKDDATA"/taskd.pid
  taskd config --force -- server.key  "$TASKDDATA"/server.key.pem
  taskd config --force -- server.cert "$TASKDDATA"/server.cert.pem
  taskd config --force -- server.crl  "$TASKDDATA"/server.crl.pem
  taskd config --force -- ca.cert     "$TASKDDATA"/ca.cert.pem
fi
