#!/usr/bin/with-contenv sh
#shellcheck shell=sh

if [ "$LE_DISABLE" = "true" ]; then
  printf "Lets Encrypt is disabled, not doing anything\n"
else
  # shellcheck disable=SC1091
  . /scripts/certbot_opts

  # create certificate if it doesn't already exist (will overwrite otherwise)
  if [ ! -s /etc/letsencrypt/live/"$TASKD_DOMAIN"/privkey.pem ]; then
    certbot certonly "$CERTBOT_OPTS" &&\
    cp /etc/letsencrypt/live/"$TASKD_DOMAIN"/* /ssl_certs/
  fi
fi
